export let cardDb = [
    {
        name: "Bash",
        type: "Attack",
        rarity: "Basic",
        cost: "2",
        desc: "Deal 8 (10) damage. Apply 2 (3) Vulnerable.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Defend",
        type: "Skill",
        rarity: "Basic",
        cost: "1",
        desc: "Gain 5 (8) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Strike",
        type: "Attack",
        rarity: "Basic",
        cost: "1",
        desc: "Deal 6 (9) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Anger",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 6 (8) damage. Add a copy of this card into your discard pile.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Armaments",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 5 Block. Upgrade a card in your hand for the rest of combat.",
        desc_upgraded: "Gain 5 Block. Upgrade all cards in your hand for the rest of combat.",
        char: "IRONCLAD",
    },
    {
        name: "Body Slam",
        type: "Attack",
        rarity: "Common",
        cost: "1 (0)",
        desc: "Deal damage equal to your Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Clash",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Can only be played if every card in your hand is an Attack. Deal 14 (18) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Cleave",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 8 (11) damage to ALL enemies.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Clothesline",
        type: "Attack",
        rarity: "Common",
        cost: "2",
        desc: "Deal 12 (14) damage. Apply 2 (3) Weak.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Flex",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain 2 (4) Strength. At the end of this turn, lose 2 (4) Strength.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Havoc",
        type: "Skill",
        rarity: "Common",
        cost: "1 (0)",
        desc: "Play the top card of your draw pile and Exhaust it.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Headbutt",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 9 (12) damage. Put a card from your discard pile on top of your draw pile.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Heavy Blade",
        type: "Attack",
        rarity: "Common",
        cost: "2",
        desc: "Deal 14 damage. Strength affects this card 3 (5) times.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Iron Wave",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Gain 5 (7) Block. Deal 5 (7) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Perfected Strike",
        type: "Attack",
        rarity: "Common",
        cost: "2",
        desc: "Deal 6 damage. Deals 2 (3) additional damage for ALL your cards containing \"Strike\".",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Pommel Strike",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 9 damage. Draw 1 card.",
        desc_upgraded: "Deal 10 damage. Draw 2 cards.",
        char: "IRONCLAD",
    },
    {
        name: "Shrug It Off",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 8 (11) Block. Draw 1 card.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Sword Boomerang",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 3 damage to a random enemy 3 (4) times.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Thunderclap",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 4 (7) damage and apply 1 Vulnerable to ALL enemies.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "True Grit",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 7 Block. Exhaust 1 card at random.",
        desc_upgraded: "Gain 9 Block. Exhaust 1 card.",
        char: "IRONCLAD",
    },
    {
        name: "Twin Strike",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 5 (7) damage twice.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Warcry",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Draw 1 card. Put a card from your hand onto the top of your draw pile. Exhaust.",
        desc_upgraded: "Draw 2 cards. Put a card from your hand onto the top of your draw pile. Exhaust.",
        char: "IRONCLAD",
    },
    {
        name: "Wild Strike",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 12 (17) damage. Shuffle a Wound into your draw pile.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Battle Trance",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Draw 3 (4) cards. You cannot draw additional cards this turn.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Blood for Blood",
        type: "Attack",
        rarity: "Uncommon",
        cost: "4 (3)",
        desc: "Costs 1 less [R] for each time you lose HP this combat. Deal 18 (22) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Bloodletting",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Lose 3 HP. Gain [R] [R].",
        desc_upgraded: "Lose 3 HP. Gain [R] [R] [R].",
        char: "IRONCLAD",
    },
    {
        name: "Burning Pact",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Exhaust 1 card. Draw 2 (3) cards.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Carnage",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Ethereal. Deal 20 (28) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Combust",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the end of your turn, lose 1 HP and deal 5 (7) damage to ALL enemies.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Dark Embrace",
        type: "Power",
        rarity: "Uncommon",
        cost: "2 (1)",
        desc: "Whenever a card is Exhausted, draw 1 card.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Disarm",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Enemy loses 2 (3) Strength. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Dropkick",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 5 (8) damage. If the enemy has Vulnerable, gain [R] and draw 1 card.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Dual Wield",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Choose an Attack or Power card. Add a copy of that card into your hand.",
        desc_upgraded: "Choose an Attack or Power card. Add 2 copies of that card into your hand.",
        char: "IRONCLAD",
    },
    {
        name: "Entrench",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2 (1)",
        desc: "Double your Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Evolve",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you draw a Status card, draw 1 card.",
        desc_upgraded: "Whenever you draw a Status card, draw 2 cards.",
        char: "IRONCLAD",
    },
    {
        name: "Feel No Pain",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever a card is Exhausted, gain 3 (4) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Fire Breathing",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you draw a Status or Curse card, deal 6 (10) damage to ALL enemies.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Flame Barrier",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 12 (16) Block. Whenever you are attacked this turn, deal 4 (6) damage back.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Ghostly Armor",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Ethereal. Gain 10 (13) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Hemokinesis",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Lose 2 HP. Deal 15 (20) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Infernal Blade",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Add a random Attack into your hand. It costs 0 this turn. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Inflame",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 2 (3) Strength.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Intimidate",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Apply 1 (2) Weak to ALL enemies. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Metallicize",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the end of your turn, gain 3 (4) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Power Through",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Add 2 Wounds into your hand. Gain 15 (20) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Pummel",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 2 damage 4 (5) times. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Rage",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Whenever you play an Attack this turn, gain 3 (5) Block.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Rampage",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 8 damage. Increase this card's damage by 5 (8) this combat.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Reckless Charge",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 7 (10) damage. Shuffle a Dazed into your draw pile.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Rupture",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you lose HP from a card, gain 1 (2) Strength.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Searing Blow",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 12 (16) damage. Can be Upgraded any number of times.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Second Wind",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Exhaust all non-Attack cards in your hand. Gain 5 (7) Block for each card Exhausted.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Seeing Red",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Gain [R] [R]. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Sentinel",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 5 Block. If this card is Exhausted, gain [R] [R].",
        desc_upgraded: "Gain 8 Block. If this card is Exhausted, gain [R] [R] [R].",
        char: "IRONCLAD",
    },
    {
        name: "Sever Soul",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Exhaust all non-Attack cards in your hand. Deal 16 (22) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Shockwave",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Apply 3 (5) Weak and Vulnerable to ALL enemies. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Spot Weakness",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "If the enemy intends to attack, gain 3 (4) Strength.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Uppercut",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 13 damage. Apply 1 (2) Weak. Apply 1 (2) Vulnerable.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Whirlwind",
        type: "Attack",
        rarity: "Uncommon",
        cost: "X",
        desc: "Deal 5 (8) damage to ALL enemies X times.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Barricade",
        type: "Power",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "Block is not removed at the start of your turn.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Berserk",
        type: "Power",
        rarity: "Rare",
        cost: "0",
        desc: "Gain 2 (1) Vulnerable. At the start of your turn, gain [R].",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Bludgeon",
        type: "Attack",
        rarity: "Rare",
        cost: "3",
        desc: "Deal 32 (42) damage.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Brutality",
        type: "Power",
        rarity: "Rare",
        cost: "0",
        desc: "At the start of your turn, lose 1 HP and draw 1 card.",
        desc_upgraded: "Innate. At the start of your turn, lose 1 HP and draw 1 card.",
        char: "IRONCLAD",
    },
    {
        name: "Corruption",
        type: "Power",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "Skills cost 0. Whenever you play a Skill, Exhaust it.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Demon Form",
        type: "Power",
        rarity: "Rare",
        cost: "3",
        desc: "At the start of your turn, gain 2 (3) Strength.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Double Tap",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "This turn, your next Attack is played twice.",
        desc_upgraded: "This turn, your next 2 Attacks are played twice.",
        char: "IRONCLAD",
    },
    {
        name: "Exhume",
        type: "Skill",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "Put a card from your exhaust pile into your hand. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Feed",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 10 (12) damage. If Fatal, raise your Max HP by 3 (4). Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Fiend Fire",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Exhaust your hand. Deal 7 (10) damage for each card Exhausted. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Immolate",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 21 (28) damage to ALL enemies. Add a Burn into your discard pile.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Impervious",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Gain 30 (40) Block. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Juggernaut",
        type: "Power",
        rarity: "Rare",
        cost: "2",
        desc: "Whenever you gain Block, deal 5 (7) damage to a random enemy.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Limit Break",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "Double your Strength. Exhaust.",
        desc_upgraded: "Double your Strength.",
        char: "IRONCLAD",
    },
    {
        name: "Offering",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Lose 6 HP. Gain [R] [R]. Draw 3 (5) cards. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Reaper",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 4 (5) damage to ALL enemies. Heal HP equal to unblocked damage. Exhaust.",
        desc_upgraded: "",
        char: "IRONCLAD",
    },
    {
        name: "Defend",
        type: "Skill",
        rarity: "Basic",
        cost: "1",
        desc: "Gain 5 (8) Block.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Neutralize",
        type: "Attack",
        rarity: "Basic",
        cost: "0",
        desc: "Deal 3 (4) damage. Apply 1 (2) Weak.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Strike",
        type: "Attack",
        rarity: "Basic",
        cost: "1",
        desc: "Deal 6 (9) damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Survivor",
        type: "Skill",
        rarity: "Basic",
        cost: "1",
        desc: "Gain 8 (11) Block. Discard 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Acrobatics",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Draw 3 (4) cards. Discard 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Backflip",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 5 (8) Block. Draw 2 cards.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Bane",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (10) damage. If the enemy has Poison, deal 7 (10) damage again.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Blade Dance",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Add 3 (4) Shivs into your hand.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Cloak and Dagger",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 6 Block. Add 1 Shiv into your hand.",
        desc_upgraded: "Gain 6 Block. Add 2 Shivs into your hand.",
        char: "SILENT",
    },
    {
        name: "Dagger Spray",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 4 (6) damage to ALL enemies twice.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Dagger Throw",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 9 (12) damage. Draw 1 card. Discard 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Deadly Poison",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Apply 5 (7) Poison.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Deflect",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain 4 (7) Block.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Dodge and Roll",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 4 (6) Block. Next turn, gain 4 (6) Block.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Flying Knee",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 8 (11) damage. Next turn, gain [G].",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Outmaneuver",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Next turn, gain [G] [G].",
        desc_upgraded: "Next turn, gain [G] [G] [G].",
        char: "SILENT",
    },
    {
        name: "Piercing Wail",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "ALL enemies lose 6 (8) Strength this turn. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Poisoned Stab",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 6 (8) damage. Apply 3 (4) Poison.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Prepared",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Draw 1 card. Discard 1 card.",
        desc_upgraded: "Draw 2 cards. Discard 2 cards.",
        char: "SILENT",
    },
    {
        name: "Quick Slash",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 8 (12) damage. Draw 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Slice",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 6 (9) damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Sneaky Strike",
        type: "Attack",
        rarity: "Common",
        cost: "2",
        desc: "Deal 12 (16) damage. If you have discarded a card this turn, gain [G] [G].",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Sucker Punch",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (9) damage. Apply 1 (2) Weak.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Accuracy",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Shivs deal 4 (6) additional damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "All-Out Attack",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 10 (14) damage to ALL enemies. Discard 1 card at random.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Backstab",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Innate. Deal 11 (15) damage. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Blur",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 5 (8) Block. Block is not removed at the start of your next turn.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Bouncing Flask",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Apply 3 Poison to a random enemy 3 (4) times.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Calculated Gamble",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Discard your hand, then draw that many cards. Exhaust.",
        desc_upgraded: "Discard your hand, then draw that many cards.",
        char: "SILENT",
    },
    {
        name: "Caltrops",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you are attacked, deal 3 (5) damage back.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Catalyst",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Double the enemy's Poison. Exhaust.",
        desc_upgraded: "Triple the enemy's Poison. Exhaust.",
        char: "SILENT",
    },
    {
        name: "Choke",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 12 damage. Whenever you play a card this turn, the enemy loses 3 (5) HP.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Concentrate",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Discard 3 (2) cards. Gain [G] [G].",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Crippling Cloud",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Apply 4 (7) Poison and 2 Weak to ALL enemies. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Dash",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 10 (13) Block. Deal 10 (13) damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Distraction",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Add a random Skill into your hand. It costs 0 this turn. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Endless Agony",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 4 (6) damage. Whenever you draw this card, add a copy of it into your hand. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Escape Plan",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Draw 1 card. If you draw a Skill, gain 3 (5) Block.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Eviscerate",
        type: "Attack",
        rarity: "Uncommon",
        cost: "3",
        desc: "Costs 1 less [G] for each card discarded this turn. Deal 7 (9) damage 3 times.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Expertise",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Draw cards until you have 6 (7) in your hand.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Finisher",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 6 (8) damage for each Attack played this turn.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Flechettes",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 4 (6) damage for each Skill in your hand.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Footwork",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 2 (3) Dexterity.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Heel Hook",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 5 (8) damage. If the enemy has Weak, gain [G] and draw 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Infinite Blades",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your turn, add a Shiv into your hand.",
        desc_upgraded: "Innate. At the start of your turn, add a Shiv into your hand.",
        char: "SILENT",
    },
    {
        name: "Leg Sweep",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Apply 2 (3) Weak. Gain 11 (14) Block.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Masterful Stab",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Costs 1 additional [G] for each time you lose HP this combat. Deal 12 (16) damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Noxious Fumes",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your turn, apply 2 (3) Poison to ALL enemies.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Predator",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 15 (20) damage. Next turn, draw 2 additional cards.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Reflex",
        type: "Skill",
        rarity: "Uncommon",
        cost: "Unplayable",
        desc: "Unplayable. If this card is discarded from your hand, draw 2 cards.",
        desc_upgraded: "Unplayable. If this card is discarded from your hand, draw 3 cards.",
        char: "SILENT",
    },
    {
        name: "Riddle with Holes",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 3 (4) damage 5 times.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Setup",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Put a card from your hand on top of your draw pile. It costs 0 until played.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Skewer",
        type: "Attack",
        rarity: "Uncommon",
        cost: "X",
        desc: "Deal 7 (10) damage X times.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Tactician",
        type: "Skill",
        rarity: "Uncommon",
        cost: "Unplayable",
        desc: "Unplayable. If this card is discarded from your hand, gain [G].",
        desc_upgraded: "Unplayable. If this card is discarded from your hand, gain [G] [G].",
        char: "SILENT",
    },
    {
        name: "Terror",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Apply 99 Vulnerable. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Well-Laid Plans",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the end of your turn, Retain up to 1 card.",
        desc_upgraded: "At the end of your turn, Retain up to 2 cards.",
        char: "SILENT",
    },
    {
        name: "A Thousand Cuts",
        type: "Power",
        rarity: "Rare",
        cost: "2",
        desc: "Whenever you play a card, deal 1 (2) damage to ALL enemies.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Adrenaline",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Gain [G]. Draw 2 cards. Exhaust.",
        desc_upgraded: "Gain [G] [G]. Draw 2 cards. Exhaust.",
        char: "SILENT",
    },
    {
        name: "After Image",
        type: "Power",
        rarity: "Rare",
        cost: "1",
        desc: "Whenever you play a card, gain 1 Block.",
        desc_upgraded: "Innate. Whenever you play a card, gain 1 Block.",
        char: "SILENT",
    },
    {
        name: "Alchemize",
        type: "Skill",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "Obtain a random potion. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Bullet Time",
        type: "Skill",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "You cannot draw additional cards this turn. Reduce the cost of all cards in your hand to 0 this turn.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Burst",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "This turn, your next Skill is played twice.",
        desc_upgraded: "This turn, your next 2 Skills are played twice.",
        char: "SILENT",
    },
    {
        name: "Corpse Explosion",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Apply 6 (9) Poison. When the enemy dies, deal damage equal to its Max HP to ALL enemies.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Die Die Die",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 13 (17) damage to ALL enemies. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Doppelganger",
        type: "Skill",
        rarity: "Rare",
        cost: "X",
        desc: "Next turn, draw X cards and gain X [G]. Exhaust.",
        desc_upgraded: "Next turn, draw X+1 cards and gain X+1 [G]. Exhaust.",
        char: "SILENT",
    },
    {
        name: "Envenom",
        type: "Power",
        rarity: "Rare",
        cost: "2 (1)",
        desc: "Whenever an Attack deals unblocked damage, apply 1 Poison.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Glass Knife",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 8 (12) damage twice. Decrease the damage of this card by 2 this combat.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Grand Finale",
        type: "Attack",
        rarity: "Rare",
        cost: "0",
        desc: "Can only be played if there are no cards in your draw pile. Deal 50 (60) damage to ALL enemies.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Malaise",
        type: "Skill",
        rarity: "Rare",
        cost: "X",
        desc: "Enemy loses X Strength. Apply X Weak. Exhaust.",
        desc_upgraded: "Enemy loses X+1 Strength. Apply X+1 Weak. Exhaust.",
        char: "SILENT",
    },
    {
        name: "Nightmare",
        type: "Skill",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "Choose a card. Next turn, add 3 copies of that card into your hand. Exhaust.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Phantasmal Killer",
        type: "Skill",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "Next turn, your Attacks deal double damage.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Storm of Steel",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "Discard your hand. Add 1 Shiv into your hand for each card discarded.",
        desc_upgraded: "Discard your hand. Add 1 Shiv+ into your hand for each card discarded.",
        char: "SILENT",
    },
    {
        name: "Tools of the Trade",
        type: "Power",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "At the start of your turn, draw 1 card and discard 1 card.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Unload",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 14 (18) damage. Discard all non-Attack cards in your hand.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Wraith Form",
        type: "Power",
        rarity: "Rare",
        cost: "3",
        desc: "Gain 2 (3) Intangible. At the end of your turn, lose 1 Dexterity.",
        desc_upgraded: "",
        char: "SILENT",
    },
    {
        name: "Defend",
        type: "Skill",
        rarity: "Basic",
        cost: "1",
        desc: "Gain 5 (8) Block.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Dualcast",
        type: "Skill",
        rarity: "Basic",
        cost: "1 (0)",
        desc: "Evoke your next Orb twice.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Strike",
        type: "Attack",
        rarity: "Basic",
        cost: "1",
        desc: "Deal 6 (9) damage.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Zap",
        type: "Skill",
        rarity: "Basic",
        cost: "1 (0)",
        desc: "Channel 1 Lightning.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Ball Lightning",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (10) damage. Channel 1 Lightning.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Barrage",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 4 (6) damage for each Channeled Orb.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Beam Cell",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 3 (4) damage. Apply 1 (2) Vulnerable.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Charge Battery",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 7 (10) Block. Next turn, gain [B].",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Claw",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 3 (5) damage. Increase the damage of ALL Claw cards by 2 this combat.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Cold Snap",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 6 (9) damage. Channel 1 Frost.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Compile Driver",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (10) damage. Draw 1 card for each unique Orb you have.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Coolheaded",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Channel 1 Frost. Draw 1 card.",
        desc_upgraded: "Channel 1 Frost. Draw 2 cards.",
        char: "DEFECT",
    },
    {
        name: "Go for the Eyes",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 3 (4) damage. If the enemy intends to attack, apply 1 (2) Weak.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Hologram",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 3 Block. Put a card from your discard pile into your hand. Exhaust.",
        desc_upgraded: "Gain 5 Block. Put a card from your discard pile into your hand.",
        char: "DEFECT",
    },
    {
        name: "Leap",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 9 (12) Block.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Rebound",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 9 (12) damage. Put the next card you play this turn on top of your draw pile.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Recursion",
        type: "Skill",
        rarity: "Common",
        cost: "1 (0)",
        desc: "Evoke your next Orb. Channel the Orb that was just Evoked.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Stack",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain Block equal to the number of cards in your discard pile.",
        desc_upgraded: "Gain Block equal to the number of cards in your discard pile +3.",
        char: "DEFECT",
    },
    {
        name: "Steam Barrier",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain 6 (8) Block. Decrease this card's Block by 1 this combat.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Streamline",
        type: "Attack",
        rarity: "Common",
        cost: "2",
        desc: "Deal 15 (20) damage. Reduce this card's cost by 1 this combat.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Sweeping Beam",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 6 (9) damage to ALL enemies. Draw 1 card.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "TURBO",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain [B] [B]. Add a Void into your discard pile.",
        desc_upgraded: "Gain [B] [B] [B]. Add a Void into your discard pile.",
        char: "DEFECT",
    },
    {
        name: "Aggregate",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain [B] for every 4 (3) cards in your draw pile.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Auto-Shields",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "If you have no Block, gain 11 (15) Block.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Blizzard",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal damage equal to 2 (3) times the number of Frost Channeled this combat to ALL enemies.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Boot Sequence",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Innate. Gain 10 (13) Block. Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Bullseye",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 8 (11) damage. Apply 2 (3) Lock-On.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Capacitor",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 2 (3) Orb slots.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Chaos",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Channel 1 random Orb.",
        desc_upgraded: "Channel 2 random Orbs.",
        char: "DEFECT",
    },
    {
        name: "Chill",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Channel 1 Frost for each enemy in combat. Exhaust.",
        desc_upgraded: "Innate. Channel 1 Frost for each enemy in combat. Exhaust.",
        char: "DEFECT",
    },
    {
        name: "Consume",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 2 (3) Focus. Lose 1 Orb slot.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Darkness",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Channel 1 Dark.",
        desc_upgraded: "Channel 1 Dark. Trigger the passive ability of all Dark orbs.",
        char: "DEFECT",
    },
    {
        name: "Defragment",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 1 (2) Focus.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Doom and Gloom",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 10 (14) damage to ALL enemies. Channel 1 Dark.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Double Energy",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Double your Energy. Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Equilibrium",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 13 (16) Block. Retain your hand this turn.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "FTL",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 5 (6) damage. If you have played less than 3 (4) cards this turn, draw 1 card.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Force Field",
        type: "Skill",
        rarity: "Uncommon",
        cost: "4",
        desc: "Costs 1 less [B] for each Power card played this combat. Gain 12 (16) Block.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Fusion",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2 (1)",
        desc: "Channel 1 Plasma.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Genetic Algorithm",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 1 Block. Permanently increase this card's Block by 2 (3). Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Glacier",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 7 (10) Block. Channel 2 Frost.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Heatsinks",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you play a Power card, draw 1 card.",
        desc_upgraded: "Whenever you play a Power card, draw 2 cards.",
        char: "DEFECT",
    },
    {
        name: "Hello World",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your turn, add a random Common card into your hand.",
        desc_upgraded: "Innate. At the start of your turn, add a random Common card into your hand.",
        char: "DEFECT",
    },
    {
        name: "Loop",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your turn, trigger the passive ability of your next Orb.",
        desc_upgraded: "At the start of your turn, trigger the passive ability of your next Orb 2 times.",
        char: "DEFECT",
    },
    {
        name: "Melter",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Remove all Block from the enemy. Deal 10 (14) damage.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Overclock",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Draw 2 (3) cards. Add a Burn into your discard pile.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Recycle",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Exhaust a card. Gain [B] equal to its cost.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Reinforced Body",
        type: "Skill",
        rarity: "Uncommon",
        cost: "X",
        desc: "Gain 7 (9) Block X times.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Reprogram",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Lose 1 (2) Focus. Gain 1 (2) Strength. Gain 1 (2) Dexterity.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Rip and Tear",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 7 (9) damage to a random enemy twice.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Scrape",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 7 (10) damage. Draw 4 (5) cards. Discard all cards drawn this way that do not cost 0.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Self Repair",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the end of combat, heal 7 (10) HP.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Skim",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Draw 3 (4) cards.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Static Discharge",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you receive unblocked attack damage, Channel 1 (2) Lightning.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Storm",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you play a Power card, Channel 1 Lightning.",
        desc_upgraded: "Innate. Whenever you play a Power card, Channel 1 Lightning.",
        char: "DEFECT",
    },
    {
        name: "Sunder",
        type: "Attack",
        rarity: "Uncommon",
        cost: "3",
        desc: "Deal 24 (32) damage. If this kills an enemy, gain [B] [B] [B].",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Tempest",
        type: "Skill",
        rarity: "Uncommon",
        cost: "X",
        desc: "Channel X Lightning. Exhaust.",
        desc_upgraded: "Channel X+1 Lightning. Exhaust.",
        char: "DEFECT",
    },
    {
        name: "White Noise",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Add a random Power card into your hand. It costs 0 this turn. Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "All for One",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 10 (14) damage. Put all cost 0 cards from your discard pile into your hand.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Amplify",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "This turn, your next Power card is played twice.",
        desc_upgraded: "This turn, your next 2 Power cards are played twice.",
        char: "DEFECT",
    },
    {
        name: "Biased Cognition",
        type: "Power",
        rarity: "Rare",
        cost: "1",
        desc: "Gain 4 (5) Focus. At the start of your turn, lose 1 Focus.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Buffer",
        type: "Power",
        rarity: "Rare",
        cost: "2",
        desc: "Prevent the next time you would lose HP.",
        desc_upgraded: "Prevent the next 2 times you would lose HP.",
        char: "DEFECT",
    },
    {
        name: "Core Surge",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 11 (15) damage. Gain 1 Artifact. Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Creative AI",
        type: "Power",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "At the start of your turn, add a random Power card into your hand.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Echo Form",
        type: "Power",
        rarity: "Rare",
        cost: "3",
        desc: "Ethereal. The first card you play each turn is played twice.",
        desc_upgraded: "The first card you play each turn is played twice.",
        char: "DEFECT",
    },
    {
        name: "Electrodynamics",
        type: "Power",
        rarity: "Rare",
        cost: "2",
        desc: "Lightning now hits ALL enemies. Channel 2 (3) Lightning.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Fission",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Remove all your Orbs. Gain [B] and draw 1 card for each Orb removed. Exhaust.",
        desc_upgraded: "Evoke all your Orbs. Gain [B] and draw 1 card for each Orb Evoked. Exhaust.",
        char: "DEFECT",
    },
    {
        name: "Hyperbeam",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 26 (34) damage to ALL enemies. Lose 3 Focus.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Machine Learning",
        type: "Power",
        rarity: "Rare",
        cost: "1",
        desc: "At the start of your turn, draw 1 additional card.",
        desc_upgraded: "Innate. At the start of your turn, draw 1 additional card.",
        char: "DEFECT",
    },
    {
        name: "Meteor Strike",
        type: "Attack",
        rarity: "Rare",
        cost: "5",
        desc: "Deal 24 (30) damage. Channel 3 Plasma.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Multi-Cast",
        type: "Skill",
        rarity: "Rare",
        cost: "X",
        desc: "Evoke your next Orb X times.",
        desc_upgraded: "Evoke your next Orb X+1 times.",
        char: "DEFECT",
    },
    {
        name: "Rainbow",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Channel 1 Lightning. Channel 1 Frost. Channel 1 Dark. Exhaust.",
        desc_upgraded: "Channel 1 Lightning. Channel 1 Frost. Channel 1 Dark.",
        char: "DEFECT",
    },
    {
        name: "Reboot",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Shuffle ALL your cards into your draw pile. Draw 4 (6) cards. Exhaust.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Seek",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Put 1 card from your draw pile into your hand. Exhaust.",
        desc_upgraded: "Put 2 cards from your draw pile into your hand. Exhaust.",
        char: "DEFECT",
    },
    {
        name: "Thunder Strike",
        type: "Attack",
        rarity: "Rare",
        cost: "3",
        desc: "Deal 7 (9) damage to a random enemy for each Lightning Channeled this combat.",
        desc_upgraded: "",
        char: "DEFECT",
    },
    {
        name: "Defend",
        type: "Skill",
        rarity: "Basic",
        cost: "1",
        desc: "Gain 5 (8) Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Eruption",
        type: "Attack",
        rarity: "Basic",
        cost: "2 (1)",
        desc: "Deal 9 damage. Enter Wrath.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Strike",
        type: "Attack",
        rarity: "Basic",
        cost: "1",
        desc: "Deal 6 (9) damage.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Vigilance",
        type: "Skill",
        rarity: "Basic",
        cost: "2",
        desc: "Gain 8 (12) Block. Enter Calm.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Bowling Bash",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (10) damage for each enemy in combat.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Consecrate",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 5 (8) damage to ALL enemies.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Crescendo",
        type: "Skill",
        rarity: "Common",
        cost: "1 (0)",
        desc: "Retain. Enter Wrath. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Crush Joints",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 8 (10) damage. If the last card played this combat was a Skill, apply 1 (2) Vulnerable.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Cut Through Fate",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (9) damage. Scry 2 (3). Draw 1 card.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Empty Body",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 7 (10) Block. Exit your Stance.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Empty Fist",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 9 (14) damage. Exit your Stance.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Evaluate",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 6 (10) Block. Shuffle an Insight into your draw pile.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Flurry of Blows",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Deal 4 (6) damage. Whenever you change Stances, return this from the discard pile to your hand.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Flying Sleeves",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Retain. Deal 4 (6) damage twice.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Follow-Up",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 7 (11) damage. If the last card played this combat was an Attack, gain [W].",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Halt",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain 3 (4) Block. If you are in Wrath, gain 9 (14) additional Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Just Lucky",
        type: "Attack",
        rarity: "Common",
        cost: "0",
        desc: "Scry 1 (2). Gain 2 (3) Block. Deal 3 (4) damage.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Pressure Points",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Apply 8 (11) Mark. ALL enemies lose HP equal to their Mark.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Prostrate",
        type: "Skill",
        rarity: "Common",
        cost: "0",
        desc: "Gain 2 (3) Mantra. Gain 4 Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Protect",
        type: "Skill",
        rarity: "Common",
        cost: "2",
        desc: "Retain. Gain 12 (16) Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Sash Whip",
        type: "Attack",
        rarity: "Common",
        cost: "1",
        desc: "Deal 8 (10) damage. If the last card played this combat was an Attack, apply 1 (2) Weak.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Third Eye",
        type: "Skill",
        rarity: "Common",
        cost: "1",
        desc: "Gain 7 (9) Block. Scry 3 (5).",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Tranquility",
        type: "Skill",
        rarity: "Common",
        cost: "1 (0)",
        desc: "Retain. Enter Calm. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Battle Hymn",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of each turn, add a Smite into your hand.",
        desc_upgraded: "Innate. At the start of each turn, add a Smite into your hand.",
        char: "WATCHER",
    },
    {
        name: "Carve Reality",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 6 (10) damage. Add a Smite into your hand.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Collect",
        type: "Skill",
        rarity: "Uncommon",
        cost: "X",
        desc: "Put a Miracle+ into your hand at the start of your next X turns. Exhaust.",
        desc_upgraded: "Put a Miracle+ into your hand at the start of your next X+1 turns. Exhaust.",
        char: "WATCHER",
    },
    {
        name: "Conclude",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 12 (16) damage to ALL enemies. End your turn.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Deceive Reality",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 4 (7) Block. Add a Safety into your hand.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Empty Mind",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Draw 2 (3) cards. Exit your Stance.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Fasting",
        type: "Power",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 3 (4) Strength. Gain 3 (4) Dexterity. Gain 1 less [W] at the start of each turn.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Fear No Evil",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 8 (11) damage. If the enemy intends to Attack, enter Calm.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Foreign Influence",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Choose 1 of 3 Attacks of any color to add into your hand. Exhaust.",
        desc_upgraded: "Choose 1 of 3 Attacks of any color to add into your hand. It costs 0 this turn. Exhaust.",
        char: "WATCHER",
    },
    {
        name: "Foresight",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your turn, Scry 3 (4).",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Indignation",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "If you are in Wrath, apply 3 (5) Vulnerable to ALL enemies, otherwise enter Wrath.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Inner Peace",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "If you are in Calm, draw 3 (4) cards, otherwise enter Calm.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Like Water",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the end of your turn, if you are in Calm, gain 5 (7) Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Meditate",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Put a card from your discard pile into your hand and Retain it. Enter Calm. End your turn.",
        desc_upgraded: "Put 2 cards from your discard pile into your hand and Retain them. Enter Calm. End your turn.",
        char: "WATCHER",
    },
    {
        name: "Mental Fortress",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you change Stances, gain 4 (6) Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Nirvana",
        type: "Power",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you Scry, gain 3 (4) Block.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Perseverance",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Retain. Gain 5 (7) Block. When Retained, increase its Block by 2 (3) this combat.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Pray",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 3 (4) Mantra. Shuffle an Insight into your draw pile.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Reach Heaven",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 10 (15) damage. Shuffle a Through Violence into your draw pile.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Rushdown",
        type: "Power",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Whenever you enter Wrath, draw 2 cards.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Sanctity",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Gain 6 (9) Block. If the last card played this combat was a Skill, draw 2 cards.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Sands of Time",
        type: "Attack",
        rarity: "Uncommon",
        cost: "4",
        desc: "Retain. Deal 20 (26) damage. When Retained, lower its cost by 1 this combat.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Signature Move",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Can only be played if this is the only Attack in your hand. Deal 30 (40) damage.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Simmering Fury",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "At the start of your next turn, enter Wrath and draw 2 (3) cards.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Study",
        type: "Power",
        rarity: "Uncommon",
        cost: "2 (1)",
        desc: "At the end of your turn, shuffle an Insight into your draw pile.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Swivel",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 8 (11) Block. The next Attack you play costs 0.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Talk to the Hand",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 5 (7) damage. Whenever you attack this enemy, gain 2 (3) Block. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Tantrum",
        type: "Attack",
        rarity: "Uncommon",
        cost: "1",
        desc: "Deal 3 damage 3 (4) times. Enter Wrath. Shuffle this card into your draw pile.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Wallop",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 9 (12) damage. Gain Block equal to unblocked damage dealt.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Wave of the Hand",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Whenever you gain Block this turn, apply 1 (2) Weak to ALL enemies.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Weave",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 4 (6) damage. Whenever you Scry, return this from the discard pile to your Hand.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Wheel Kick",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Deal 15 (20) damage. Draw 2 cards.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Windmill Strike",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2",
        desc: "Retain. Deal 7 (10) damage. When Retained, increase its damage by 4 (5) this combat.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Worship",
        type: "Skill",
        rarity: "Uncommon",
        cost: "2",
        desc: "Gain 5 Mantra.",
        desc_upgraded: "Retain. Gain 5 Mantra.",
        char: "WATCHER",
    },
    {
        name: "Wreath of Flame",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Your next Attack deals 5 (8) additional damage.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Alpha",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "Shuffle a Beta into your draw pile. Exhaust.",
        desc_upgraded: "Innate. Shuffle a Beta into your draw pile. Exhaust.",
        char: "WATCHER",
    },
    {
        name: "Blasphemy",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "Enter Divinity. Die next turn. Exhaust.",
        desc_upgraded: "Retain. Enter Divinity. Die next turn. Exhaust.",
        char: "WATCHER",
    },
    {
        name: "Brilliance",
        type: "Attack",
        rarity: "Rare",
        cost: "1",
        desc: "Deal 12 (16) damage. Deals additional damage equal to Mantra gained this combat.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Conjure Blade",
        type: "Skill",
        rarity: "Rare",
        cost: "X",
        desc: "Shuffle an Expunger into your draw pile. Exhaust.",
        desc_upgraded: "Shuffle an Expunger with X+1 into your draw pile. Exhaust.",
        char: "WATCHER",
    },
    {
        name: "Deus Ex Machina",
        type: "Skill",
        rarity: "Rare",
        cost: "Unplayable",
        desc: "Unplayable. When you draw this card, add 2 (3) Miracles to your hand and Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Deva Form",
        type: "Power",
        rarity: "Rare",
        cost: "3",
        desc: "Ethereal. At the start of your turn, gain [W] and increase this gain by 1.",
        desc_upgraded: "At the start of your turn, gain [W] and increase this gain by 1.",
        char: "WATCHER",
    },
    {
        name: "Devotion",
        type: "Power",
        rarity: "Rare",
        cost: "1",
        desc: "At the start of your turn, gain 2 (3) Mantra.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Establishment",
        type: "Power",
        rarity: "Rare",
        cost: "1",
        desc: "Whenever a card is Retained, reduce its cost by 1 this combat.",
        desc_upgraded: "Innate. Whenever a card is Retained, reduce its cost by 1 this combat.",
        char: "WATCHER",
    },
    {
        name: "Judgment",
        type: "Skill",
        rarity: "Rare",
        cost: "1",
        desc: "If the enemy has 30 (40) or less HP, set their HP to 0.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Lesson Learned",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 10 (13) damage. If Fatal, Upgrade a random card in your deck. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Master Reality",
        type: "Power",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "Whenever a card is created during combat, Upgrade it.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Omniscience",
        type: "Skill",
        rarity: "Rare",
        cost: "4 (3)",
        desc: "Choose a card in your draw pile. Play the chosen card twice and exhaust it. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Ragnarok",
        type: "Attack",
        rarity: "Rare",
        cost: "3",
        desc: "Deal 5 (6) damage to a random enemy 5 (6) times.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Scrawl",
        type: "Skill",
        rarity: "Rare",
        cost: "1 (0)",
        desc: "Draw cards until your hand is full. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Spirit Shield",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Gain 3 (4) Block for each card in your hand.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Vault",
        type: "Skill",
        rarity: "Rare",
        cost: "3 (2)",
        desc: "Take an extra turn after this one. End your turn. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Wish",
        type: "Skill",
        rarity: "Rare",
        cost: "3",
        desc: "Choose one: Gain 6 (8) Plated Armor, 3 (4) Strength, or 25 (30) Gold. Exhaust.",
        desc_upgraded: "",
        char: "WATCHER",
    },
    {
        name: "Bandage Up",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Heal 4 (6) HP. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Blind",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Apply 2 Weak.",
        desc_upgraded: "Apply 2 Weak to ALL enemies.",
        char: "COLORLESS",
    },
    {
        name: "Dark Shackles",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Enemy loses 9 (15) Strength this turn. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Deep Breath",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Shuffle your discard pile into your draw pile. Draw 1 card.",
        desc_upgraded: "Shuffle your discard pile into your draw pile. Draw 2 cards.",
        char: "COLORLESS",
    },
    {
        name: "Discovery",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1",
        desc: "Choose 1 of 3 random cards to add into your hand. It costs 0 this turn. Exhaust.",
        desc_upgraded: "Choose 1 of 3 random cards to add into your hand. It costs 0 this turn.",
        char: "COLORLESS",
    },
    {
        name: "Dramatic Entrance",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Innate. Deal 8 (12) damage to ALL enemies. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Enlightenment",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Reduce the cost of all cards in your hand to 1 this turn.",
        desc_upgraded: "Reduce the cost of all cards in your hand to 1 this combat.",
        char: "COLORLESS",
    },
    {
        name: "Finesse",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Gain 2 (4) Block. Draw 1 card.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Flash of Steel",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 3 (6) damage. Draw 1 card.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Forethought",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Put a card from your hand to the bottom of your draw pile. It costs 0 until played.",
        desc_upgraded: "Put any number of cards from your hand to the bottom of your draw pile. They cost 0 until played.",
        char: "COLORLESS",
    },
    {
        name: "Good Instincts",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Gain 6 (9) Block.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Impatience",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "If you have no Attacks in your hand, draw 2 (3) cards.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Jack of All Trades",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Add 1 random Colorless card into your hand. Exhaust.",
        desc_upgraded: "Add 2 random Colorless cards into your hand. Exhaust.",
        char: "COLORLESS",
    },
    {
        name: "Madness",
        type: "Skill",
        rarity: "Uncommon",
        cost: "1 (0)",
        desc: "Reduce the cost of a random card in your hand to 0 this combat. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Mind Blast",
        type: "Attack",
        rarity: "Uncommon",
        cost: "2 (1)",
        desc: "Innate. Deal damage equal to the number of cards in your draw pile.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Panacea",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Gain 1 (2) Artifact. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Panic Button",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Gain 30 (40) Block. You cannot gain Block from cards for 2 turns. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Purity",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Exhaust up to 3 (5) cards in your hand. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Swift Strike",
        type: "Attack",
        rarity: "Uncommon",
        cost: "0",
        desc: "Deal 7 (10) damage.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Trip",
        type: "Skill",
        rarity: "Uncommon",
        cost: "0",
        desc: "Apply 2 Vulnerable.",
        desc_upgraded: "Apply 2 Vulnerable to ALL enemies.",
        char: "COLORLESS",
    },
    {
        name: "Apotheosis",
        type: "Skill",
        rarity: "Rare",
        cost: "2 (1)",
        desc: "Upgrade ALL your cards for the rest of combat. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Chrysalis",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Shuffle 3 (5) random Skills into your draw pile. They cost 0 this combat. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Hand of Greed",
        type: "Attack",
        rarity: "Rare",
        cost: "2",
        desc: "Deal 20 (25) damage. If Fatal, gain 20 (25) Gold.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Magnetism",
        type: "Power",
        rarity: "Rare",
        cost: "2 (1)",
        desc: "At the start of your turn, add a random Colorless card into your hand.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Master of Strategy",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Draw 3 (4) cards. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Mayhem",
        type: "Power",
        rarity: "Rare",
        cost: "2 (1)",
        desc: "At the start of your turn, play the top card of your draw pile.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Metamorphosis",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "Shuffle 3 (5) random Attacks into your draw pile. They cost 0 this combat. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Panache",
        type: "Power",
        rarity: "Rare",
        cost: "0",
        desc: "Every time you play 5 cards in a single turn, deal 10 (14) damage to ALL enemies.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Sadistic Nature",
        type: "Power",
        rarity: "Rare",
        cost: "0",
        desc: "Whenever you apply a debuff to an enemy, they take 5 (7) damage.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Secret Technique",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Put a Skill from your draw pile into your hand. Exhaust.",
        desc_upgraded: "Put a Skill from your draw pile into your hand.",
        char: "COLORLESS",
    },
    {
        name: "Secret Weapon",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Put an Attack from your draw pile into your hand. Exhaust.",
        desc_upgraded: "Put an Attack from your draw pile into your hand.",
        char: "COLORLESS",
    },
    {
        name: "The Bomb",
        type: "Skill",
        rarity: "Rare",
        cost: "2",
        desc: "At the end of 3 turns, deal 40 (50) damage to ALL enemies.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Thinking Ahead",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Draw 2 cards. Put a card from your hand on top of your draw pile. Exhaust.",
        desc_upgraded: "Draw 2 cards. Put a card from your hand on top of your draw pile.",
        char: "COLORLESS",
    },
    {
        name: "Transmutation",
        type: "Skill",
        rarity: "Rare",
        cost: "X",
        desc: "Add X random Colorless cards into your hand. They cost 0 this turn. Exhaust.",
        desc_upgraded: "Add X random Upgraded Colorless cards into your hand. They cost 0 this turn. Exhaust.",
        char: "COLORLESS",
    },
    {
        name: "Violence",
        type: "Skill",
        rarity: "Rare",
        cost: "0",
        desc: "Put 3 (4) random Attacks from your draw pile into your hand. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Apparition",
        type: "Skill",
        rarity: "Special",
        cost: "1",
        desc: "Ethereal. Gain 1 Intangible. Exhaust.",
        desc_upgraded: "Gain 1 Intangible. Exhaust.",
        char: "COLORLESS",
    },
    {
        name: "Become Almighty",
        type: "Power",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Gain 3 (4) Strength.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Beta",
        type: "Skill",
        rarity: "Special",
        cost: "2 (1)",
        desc: "Shuffle an Omega into your draw pile. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Bite",
        type: "Attack",
        rarity: "Special",
        cost: "1",
        desc: "Deal 7 (8) damage. Heal 2 (3) HP.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Expunger",
        type: "Attack",
        rarity: "Special",
        cost: "1",
        desc: "Deal 9 (15) damage X times.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Fame and Fortune",
        type: "Skill",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Gain 25 (30) Gold.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Insight",
        type: "Skill",
        rarity: "Special",
        cost: "0",
        desc: "Retain. Draw 2 (3) cards. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "J.A.X.",
        type: "Skill",
        rarity: "Special",
        cost: "0",
        desc: "Lose 3 HP. Gain 2 (3) Strength.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Live Forever",
        type: "Power",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Gain 6 (8) Plated Armor.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Miracle",
        type: "Skill",
        rarity: "Special",
        cost: "0",
        desc: "Retain. Gain [W]. Exhaust.",
        desc_upgraded: "Retain. Gain [W] [W]. Exhaust.",
        char: "COLORLESS",
    },
    {
        name: "Omega",
        type: "Power",
        rarity: "Special",
        cost: "3",
        desc: "At the end of your turn, deal 50 (60) damage to ALL enemies.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Ritual Dagger",
        type: "Attack",
        rarity: "Special",
        cost: "1",
        desc: "Deal 15 damage. If Fatal, permanently increase this card's damage by 3 (5). Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Safety",
        type: "Skill",
        rarity: "Special",
        cost: "1",
        desc: "Retain. Gain 12 (16) Block. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Shiv",
        type: "Attack",
        rarity: "Special",
        cost: "0",
        desc: "Deal 4 (6) damage. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Smite",
        type: "Attack",
        rarity: "Special",
        cost: "1",
        desc: "Retain. Deal 12 (16) damage. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Through Violence",
        type: "Attack",
        rarity: "Special",
        cost: "0",
        desc: "Retain. Deal 20 (30) damage. Exhaust.",
        desc_upgraded: "",
        char: "COLORLESS",
    },
    {
        name: "Clumsy",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. Ethereal.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Decay",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. At the end of your turn, take 2 damage.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Doubt",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. At the end of your turn, gain 1 Weak.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Injury",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Normality",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. While in hand, you cannot play more than 3 cards this turn.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Pain",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. While in hand, lose 1 HP whenever you play another card.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Parasite",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. If transformed or removed from your deck, lose 3 Max HP.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Regret",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. At the end of your turn, lose HP equal to the number of cards in your hand.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Shame",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. At the end of your turn, gain 1 Frail.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Writhe",
        type: "Curse",
        rarity: "Curse",
        cost: "Unplayable",
        desc: "Unplayable. Innate.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Ascender's Bane",
        type: "Curse",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Unplayable. Ethereal. Cannot be removed from your deck.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Curse of the Bell",
        type: "Curse",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Unplayable. Cannot be removed from your deck.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Necronomicurse",
        type: "Curse",
        rarity: "Special",
        cost: "Unplayable",
        desc: "Unplayable. There is no escape from this Curse.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Pride",
        type: "Curse",
        rarity: "Special",
        cost: "1",
        desc: "Innate. At the end of your turn, put a copy of this card on top of your draw pile. Exhaust.",
        desc_upgraded: "",
        char: "CURSE",
    },
    {
        name: "Burn",
        type: "Status",
        rarity: "Common",
        cost: "Unplayable",
        desc: "Unplayable. At the end of your turn, take 2 damage.",
        desc_upgraded: "",
        char: "STATUS",
    },
    {
        name: "Dazed",
        type: "Status",
        rarity: "Common",
        cost: "Unplayable",
        desc: "Unplayable. Ethereal.",
        desc_upgraded: "",
        char: "STATUS",
    },
    {
        name: "Slimed",
        type: "Status",
        rarity: "Common",
        cost: "1",
        desc: "Exhaust.",
        desc_upgraded: "",
        char: "STATUS",
    },
    {
        name: "Void",
        type: "Status",
        rarity: "Common",
        cost: "Unplayable",
        desc: "Unplayable. Ethereal. Whenever this card is drawn, lose 1 Energy.",
        desc_upgraded: "",
        char: "STATUS",
    },
    {
        name: "Wound",
        type: "Status",
        rarity: "Common",
        cost: "Unplayable",
        desc: "Unplayable.",
        desc_upgraded: "",
        char: "STATUS",
    },
]
