export let floors = [
    {
        floorNum: 0,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 1,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 2,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 3,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 4,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 5,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 6,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 7,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 8,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 9,
        act: 1,
        desc: 'Treasure Room',
        disabled: true,
    },
    {
        floorNum: 10,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 11,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 12,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 13,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 14,
        act: 1,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 15,
        act: 1,
        desc: 'Rest Site',
        disabled: false,
    },
    {
        floorNum: 16,
        act: 1,
        desc: 'Boss Battle',
        disabled: false,
    },
    {
        floorNum: 17,
        act: 1,
        desc: 'Boss Chest',
        disabled: true,
    },
    {
        floorNum: 18,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 19,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 20,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 21,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 22,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 23,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 24,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 25,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 26,
        act: 2,
        desc: 'Treasure Room',
        disabled: true,
    },
    {
        floorNum: 27,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 28,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 29,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 30,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 31,
        act: 2,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 32,
        act: 2,
        desc: 'Rest Site',
        disabled: false,
    },
    {
        floorNum: 33,
        act: 2,
        desc: 'Boss Battle',
        disabled: false,
    },
    {
        floorNum: 34,
        act: 2,
        desc: 'Boss Chest',
        disabled: true,
    },
    {
        floorNum: 35,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 36,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 37,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 38,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 39,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 40,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 41,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 42,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 43,
        act: 3,
        desc: 'Treasure Room',
        disabled: false,
    },
    {
        floorNum: 44,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 45,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 46,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 47,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 48,
        act: 3,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 49,
        act: 3,
        desc: 'Rest Site',
        disabled: false,
    },
    {
        floorNum: 50,
        act: 3,
        desc: 'Boss Battle',
        disabled: true,
    },
    {
        floorNum: 51,
        act: 4,
        desc: '',
        disabled: false,
    },
    {
        floorNum: 52,
        act: 4,
        desc: 'Rest Site',
        disabled: false,
    },
    {
        floorNum: 53,
        act: 4,
        desc: 'Merchant',
        disabled: false,
    },
    {
        floorNum: 54,
        act: 4,
        desc: 'Shield and Spear',
        disabled: false,
    },
    {
        floorNum: 55,
        act: 4,
        desc: 'Corrupt Heart',
        disabled: true,
    },
];
