const nameMap: [string, string][] = [
    ["Akabeko", "Akabeko"],
    ["Anchor", "Anchor"],
    ["Ancient Tea Set", "Ancient Tea Set"],
    ["Anger", "Anger"],
    ["Apotheosis", "Apotheosis"],
    ["Armaments", "Armaments"],
    ["Art of War", "Art of War"],
    ["AscendersBane", "Ascender's Bane"],
    ["Astrolabe", "Astrolabe"],
    ["Bag of Marbles", "Bag of Marbles"],
    ["Bag of Preparation", "Bag of Preparation"],
    ["Bandage Up", "Bandage Up"],
    ["Barricade", "Barricade"],
    ["Bash", "Bash"],
    ["Battle Trance", "Battle Trance"],
    ["Berserk", "Berserk"],
    ["Bird Faced Urn", "Bird Faced Urn"],
    ["Bite", "Bite"],
    ["Black Blood", "Black Blood"],
    ["Black Star", "Black Star"],
    ["Blind", "Blind"],
    ["Blood Vial", "Blood Vial"],
    ["Blood for Blood", "Blood for Blood"],
    ["Bloodletting", "Bloodletting"],
    ["Bloody Idol", "Bloody Idol"],
    ["Bludgeon", "Bludgeon"],
    ["Blue Candle", "Blue Candle"],
    ["Body Slam", "Body Slam"],
    ["Boot", "Boot"],
    ["Bottled Flame", "Bottled Flame"],
    ["Bottled Lightning", "Bottled Lightning"],
    ["Bottled Tornado", "Bottled Tornado"],
    ["Brimstone", "Brimstone"],
    ["Bronze Scales", "Bronze Scales"],
    ["Brutality", "Brutality"],
    ["Burning Blood", "Burning Blood"],
    ["Burning Pact", "Burning Pact"],
    ["Busted Crown", "Busted Crown"],
    ["Calipers", "Calipers"],
    ["Calling Bell", "Calling Bell"],
    ["CaptainsWheel", "Captains Wheel"],
    ["Carnage", "Carnage"],
    ["Centennial Puzzle", "Centennial Puzzle"],
    ["CeramicFish", "Ceramic Fish"],
    ["Champion Belt", "Champion Belt"],
    ["Charon's Ashes", "Charon's Ashes"],
    ["Chemical X", "Chemical X"],
    ["Chrysalis", "Chrysalis"],
    ["Clash", "Clash"],
    ["Cleave", "Cleave"],
    ["ClockworkSouvenir", "Clockwork Souvenir"],
    ["Clothesline", "Clothesline"],
    ["Clumsy", "Clumsy"],
    ["Coffee Dripper", "Coffee Dripper"],
    ["Combust", "Combust"],
    ["Corruption", "Corruption"],
    ["CultistMask", "Cultist Mask"],
    ["CurseOfTheBell", "Curse of The Bell"],
    ["Cursed Key", "Cursed Key"],
    ["Dark Embrace", "Dark Embrace"],
    ["Dark Shackles", "Dark Shackles"],
    ["Darkstone Periapt", "Darkstone Periapt"],
    ["Dead Branch", "Dead Branch"],
    ["Decay", "Decay"],
    ["Deep Breath", "Deep Breath"],
    ["Defend_R", "Defend"],
    ["Demon Form", "Demon Form"],
    ["Disarm", "Disarm"],
    ["Discovery", "Discovery"],
    ["DollysMirror", "Dollys Mirror"],
    ["Double Tap", "Double Tap"],
    ["Doubt", "Doubt"],
    ["Dramatic Entrance", "Dramatic Entrance"],
    ["Dream Catcher", "Dream Catcher"],
    ["Dropkick", "Dropkick"],
    ["Du-Vu Doll", "Du-Vu Doll"],
    ["Dual Wield", "Dual Wield"],
    ["Ectoplasm", "Ectoplasm"],
    ["Empty Cage", "Empty Cage"],
    ["Enchiridion", "Enchiridion"],
    ["Enlightenment", "Enlightenment"],
    ["Entrench", "Entrench"],
    ["Eternal Feather", "Eternal Feather"],
    ["Evolve", "Evolve"],
    ["Exhume", "Exhume"],
    ["FaceOfCleric", "Face of Cleric"],
    ["Feed", "Feed"],
    ["Feel No Pain", "Feel No Pain"],
    ["Fiend Fire", "Fiend Fire"],
    ["Finesse", "Finesse"],
    ["Fire Breathing", "Fire Breathing"],
    ["Flame Barrier", "Flame Barrier"],
    ["Flash of Steel", "Flash of Steel"],
    ["Flex", "Flex"],
    ["FossilizedHelix", "Fossilized Helix"],
    ["Frozen Egg 2", "Frozen Egg"],
    ["Frozen Eye", "Frozen Eye"],
    ["Fusion Hammer", "Fusion Hammer"],
    ["Gambling Chip", "Gambling Chip"],
    ["Ghostly", "Ghostly"],
    ["Ghostly Armor", "Ghostly Armor"],
    ["Ginger", "Ginger"],
    ["Girya", "Girya"],
    ["Golden Idol", "Golden Idol"],
    ["Good Instincts", "Good Instincts"],
    ["Gremlin Horn", "Gremlin Horn"],
    ["HandDrill", "Hand Drill"],
    ["HandOfGreed", "Hand of Greed"],
    ["Happy Flower", "Happy Flower"],
    ["Havoc", "Havoc"],
    ["Headbutt", "Headbutt"],
    ["Heavy Blade", "Heavy Blade"],
    ["Hemokinesis", "Hemokinesis"],
    ["HornCleat", "Horn Cleat"],
    ["Ice Cream", "Ice Cream"],
    ["Immolate", "Immolate"],
    ["Impatience", "Impatience"],
    ["Impervious", "Impervious"],
    ["Incense Burner", "Incense Burner"],
    ["Infernal Blade", "Infernal Blade"],
    ["Inflame", "Inflame"],
    ["Injury", "Injury"],
    ["InkBottle", "Ink Bottle"],
    ["Intimidate", "Intimidate"],
    ["Iron Wave", "Iron Wave"],
    ["J.A.X.", "J.A.X."],
    ["Jack Of All Trades", "Jack of All Trades"],
    ["Juggernaut", "Juggernaut"],
    ["Juzu Bracelet", "Juzu Bracelet"],
    ["Kunai", "Kunai"],
    ["Lantern", "Lantern"],
    ["Lee's Waffle", "Lee's Waffle"],
    ["Letter Opener", "Letter Opener"],
    ["Limit Break", "Limit Break"],
    ["Lizard Tail", "Lizard Tail"],
    ["Madness", "Madness"],
    ["Magic Flower", "Magic Flower"],
    ["Magnetism", "Magnetism"],
    ["Mango", "Mango"],
    ["Mark of Pain", "Mark of Pain"],
    ["Master of Strategy", "Master of Strategy"],
    ["Matryoshka", "Matryoshka"],
    ["MawBank", "Maw Bank"],
    ["Mayhem", "Mayhem"],
    ["MealTicket", "Meal Ticket"],
    ["Meat on the Bone", "Meat on the Bone"],
    ["Medical Kit", "Medical Kit"],
    ["Membership Card", "Membership Card"],
    ["Mercury Hourglass", "Mercury Hourglass"],
    ["Metallicize", "Metallicize"],
    ["Metamorphosis", "Metamorphosis"],
    ["Mind Blast", "Mind Blast"],
    ["Molten Egg 2", "Molten Egg"],
    ["Mummified Hand", "Mummified Hand"],
    ["MutagenicStrength", "Mutagenic Strength"],
    ["Necronomicon", "Necronomicon"],
    ["Necronomicurse", "Necronomicurse"],
    ["NeowsBlessing", "Neows Blessing"],
    ["Nilry's Codex", "Nilry's Codex"],
    ["Nloth's Gift", "N'loth's Gift"],
    ["Normality", "Normality"],
    ["Nunchaku", "Nunchaku"],
    ["Odd Mushroom", "Odd Mushroom"],
    ["Oddly Smooth Stone", "Oddly Smooth Stone"],
    ["Offering", "Offering"],
    ["Old Coin", "Old Coin"],
    ["Omamori", "Omamori"],
    ["OrangePellets", "Orange Pellets"],
    ["Orichalcum", "Orichalcum"],
    ["Ornamental Fan", "Ornamental Fan"],
    ["Orrery", "Orrery"],
    ["Pain", "Pain"],
    ["Panacea", "Panacea"],
    ["Panache", "Panache"],
    ["Pandora's Box", "Pandora's Box"],
    ["PanicButton", "Panic Button"],
    ["Pantograph", "Pantograph"],
    ["Paper Frog", "Paper Frog"],
    ["Parasite", "Parasite"],
    ["Peace Pipe", "Peace Pipe"],
    ["Pear", "Pear"],
    ["Pen Nib", "Pen Nib"],
    ["Perfected Strike", "Perfected Strike"],
    ["Philosopher's Stone", "Philosopher's Stone"],
    ["Pocketwatch", "Pocketwatch"],
    ["Pommel Strike", "Pommel Strike"],
    ["Potion Belt", "Potion Belt"],
    ["Power Through", "Power Through"],
    ["Prayer Wheel", "Prayer Wheel"],
    ["PreservedInsect", "Preserved Insect"],
    ["PrismaticShard", "Prismatic Shard"],
    ["Pummel", "Pummel"],
    ["Purity", "Purity"],
    ["Question Card", "Question Card"],
    ["Rage", "Rage"],
    ["Rampage", "Rampage"],
    ["Reaper", "Reaper"],
    ["Reckless Charge", "Reckless Charge"],
    ["Red Mask", "Red Mask"],
    ["Red Skull", "Red Skull"],
    ["Regal Pillow", "Regal Pillow"],
    ["Regret", "Regret"],
    ["RitualDagger", "Ritual Dagger"],
    ["Runic Cube", "Runic Cube"],
    ["Runic Dome", "Runic Dome"],
    ["Runic Pyramid", "Runic Pyramid"],
    ["Rupture", "Rupture"],
    ["SacredBark", "Sacred Bark"],
    ["Searing Blow", "Searing Blow"],
    ["Second Wind", "Second Wind"],
    ["Secret Technique", "Secret Technique"],
    ["Secret Weapon", "Secret Weapon"],
    ["Seeing Red", "Seeing Red"],
    ["Self Forming Clay", "Self Forming Clay"],
    ["Sentinel", "Sentinel"],
    ["Sever Soul", "Sever Soul"],
    ["Shame", "Shame"],
    ["Shockwave", "Shockwave"],
    ["Shovel", "Shovel"],
    ["Shrug It Off", "Shrug It Off"],
    ["Shuriken", "Shuriken"],
    ["Singing Bowl", "Singing Bowl"],
    ["SlaversCollar", "Slavers Collar"],
    ["Sling", "Sling"],
    ["Smiling Mask", "Smiling Mask"],
    ["Snecko Eye", "Snecko Eye"],
    ["Sozu", "Sozu"],
    ["Spot Weakness", "Spot Weakness"],
    ["SsserpentHead", "Ssserpent Head"],
    ["StoneCalendar", "Stone Calendar"],
    ["Strange Spoon", "Strange Spoon"],
    ["Strawberry", "Strawberry"],
    ["StrikeDummy", "Strike Dummy"],
    ["Strike_R", "Strike"],
    ["Sundial", "Sundial"],
    ["Swift Strike", "Swift Strike"],
    ["Sword Boomerang", "Sword Boomerang"],
    ["The Bomb", "The Bomb"],
    ["The Courier", "The Courier"],
    ["TheAbacus", "The Abacus"],
    ["Thinking Ahead", "Thinking Ahead"],
    ["Thread and Needle", "Thread and Needle"],
    ["Thunderclap", "Thunderclap"],
    ["Tiny Chest", "Tiny Chest"],
    ["Tiny House", "Tiny House"],
    ["Toolbox", "Toolbox"],
    ["Torii", "Torii"],
    ["Toxic Egg 2", "Toxic Egg"],
    ["Toy Ornithopter", "Toy Ornithopter"],
    ["Trip", "Trip"],
    ["True Grit", "True Grit"],
    ["TungstenRod", "Tungsten Rod"],
    ["Turnip", "Turnip"],
    ["Twin Strike", "Twin Strike"],
    ["Unceasing Top", "Unceasing Top"],
    ["Uppercut", "Uppercut"],
    ["Vajra", "Vajra"],
    ["Velvet Choker", "Velvet Choker"],
    ["Violence", "Violence"],
    ["War Paint", "War Paint"],
    ["Warcry", "Warcry"],
    ["WarpedTongs", "Warped Tongs"],
    ["Whetstone", "Whetstone"],
    ["Whirlwind", "Whirlwind"],
    ["White Beast Statue", "White Beast Statue"],
    ["Wild Strike", "Wild Strike"],
    ["WingedGreaves", "Winged Greaves"],
    ["Writhe", "Writhe"],
];
const reversed: [string, string][] = nameMap.map((mapping) => [mapping[1], mapping[0]]);

export const nameLookupFromIncorrect = new Map(nameMap);
export const nameLookupFromCorrect = new Map(reversed);
